package sota.utils

object Constants {

  val TRYTE_ALPHABET = "9ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  val SEED_LENGTH_MAX = 81
  var ADDRESS_LENGTH_WITHOUT_CHECKSUM = 81
  var ADDRESS_LENGTH_WITH_CHECKSUM = 90

}
